import { KioskScreenLayout } from '../../layouts/KioskScreenLayout/KioskScreenLayout';
import { Button } from '../../components/Button/Button';
import type { PrintOrder } from '../../types/kiosk';
import styles from './EmailAddressScreen.module.css';

// First Email upload screen — see docs/email-upload-requirements.md.
// Prototype simplification: `emailAddress` is a static placeholder string
// computed by the caller (App.tsx), not generated by a real catch-all
// domain + inbound webhook backend yet. The accepted-format list is a
// plausible placeholder, not a confirmed final list.
interface EmailAddressScreenProps {
  emailAddress: string;
  onNext: () => void;
  onBack: () => void;
  onHome: () => void;
  onEndSession: () => void;
  /** Current Cart contents, shown in the btn-cart popup. */
  cartItems: PrintOrder[];
  /** Navigates to the Payment Status screen from the Cart popup. */
  onProceedToPayment: () => void;
}

export function EmailAddressScreen({
  emailAddress,
  onNext,
  onBack,
  onHome,
  onEndSession,
  cartItems,
  onProceedToPayment,
}: EmailAddressScreenProps) {
  return (
    <KioskScreenLayout
      onEndSession={onEndSession}
      onBack={onBack}
      onHome={onHome}
      cartItems={cartItems}
      onProceedToPayment={onProceedToPayment}
    >
      <div className={styles.body}>
        <p className={styles.instruction}>
          Send your document as an email attachment to the address below
        </p>
        <p className={styles.address}>{emailAddress}</p>
        <p className={styles.formats}>Accepted formats: PDF, DOC, DOCX, JPG, PNG</p>
        <Button id="email-address-next" label="Next" onClick={onNext} />
      </div>
    </KioskScreenLayout>
  );
}
